/**
 * The ONLY path from src/lib/scenarios/drafts/ into the live registry
 * (src/lib/scenarios/promoted/, imported by src/lib/scenarios/index.ts).
 *
 * Run: npm run scenarios:promote -- <draft-id> --confirm
 *
 * Refuses unless: the verifier test exists, has no unfilled stub sentinel, and passes;
 * the automated audit passes; and --confirm was passed naming this exact draft. There is
 * no override flag — see src/lib/scenarios/promotion-gate.ts for the gate logic itself
 * (unit-tested independently of this script's filesystem/process orchestration).
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { spawnSync } from "node:child_process";
import { auditScenarioDraft } from "../src/lib/scenarios/audit-draft";
import { expectedValueScenarios } from "../src/lib/scenarios/expected-value";
import { promotedScenarios } from "../src/lib/scenarios/promoted";
import { evaluatePromotionGate, NOT_IMPLEMENTED_SENTINEL } from "../src/lib/scenarios/promotion-gate";
import type { Scenario } from "../src/lib/types/math-scenario";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(scriptDir, "..");
const draftsDir = join(projectRoot, "src/lib/scenarios/drafts");
const promotedDir = join(projectRoot, "src/lib/scenarios/promoted");

function toIdentifier(id: string): string {
  return "sc_" + id.replace(/[^a-zA-Z0-9]/g, "_");
}

function regeneratePromotedIndex(): void {
  const files = readdirSync(promotedDir).filter((f) => f.endsWith(".ts") && f !== "index.ts");
  const ids = files.map((f) => f.replace(/\.ts$/, "")).sort();
  const imports = ids
    .map((id) => `import { scenario as ${toIdentifier(id)} } from "./${id}";`)
    .join("\n");
  const list = ids.map(toIdentifier).join(", ");
  const content = `import type { Scenario } from "@/lib/types/math-scenario";
${imports ? imports + "\n" : ""}
/**
 * Scenarios promoted from src/lib/scenarios/drafts/ by a human via
 * scripts/promote-scenario.ts. This file is regenerated by that script — do not hand-edit
 * the array; add/remove a promoted/<id>.ts file and re-run promotion tooling instead.
 * Imported by ../index.ts. drafts/ is never imported here or anywhere else in the app.
 */
export const promotedScenarios: Scenario[] = [${list}];
`;
  writeFileSync(join(promotedDir, "index.ts"), content, "utf8");
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const confirmed = args.includes("--confirm");
  const draftId = args.find((a) => !a.startsWith("--"));

  if (!draftId) {
    console.error("Usage: npm run scenarios:promote -- <draft-id> --confirm");
    process.exit(1);
  }

  const draftPath = join(draftsDir, `${draftId}.ts`);
  const verifierPath = join(draftsDir, `${draftId}.verify.test.ts`);
  const draftExists = existsSync(draftPath);
  const verifierFileExists = existsSync(verifierPath);

  let verifierHasSentinel = false;
  let verifierPassed: boolean | null = null;
  if (verifierFileExists) {
    const verifierSource = readFileSync(verifierPath, "utf8");
    verifierHasSentinel = verifierSource.includes(NOT_IMPLEMENTED_SENTINEL);
    if (!verifierHasSentinel) {
      console.log(`Running verifier: npx vitest run ${verifierPath}`);
      const result = spawnSync("npx", ["vitest", "run", verifierPath], {
        cwd: projectRoot,
        encoding: "utf8",
        stdio: "inherit",
      });
      verifierPassed = result.status === 0;
    }
  }

  let auditPass = false;
  let auditFailures: string[] = [];
  let scenario: Scenario | null = null;
  if (draftExists) {
    const mod = (await import(pathToFileURL(draftPath).href)) as { draft: Scenario };
    scenario = mod.draft;
    const existing = [...expectedValueScenarios, ...promotedScenarios];
    const audit = auditScenarioDraft(scenario, existing);
    auditPass = audit.pass;
    auditFailures = audit.failures;
  }

  const gate = evaluatePromotionGate({
    draftExists,
    verifierFileExists,
    verifierHasSentinel,
    verifierPassed,
    auditPass,
    auditFailures,
    confirmed,
  });

  if (!gate.allowed) {
    console.error(`\nRefusing to promote "${draftId}":`);
    for (const reason of gate.reasons) console.error(`  - ${reason}`);
    process.exit(1);
  }

  if (!existsSync(promotedDir)) mkdirSync(promotedDir, { recursive: true });
  const promotedFile = `import type { Scenario } from "@/lib/types/math-scenario";

/** Promoted from src/lib/scenarios/drafts/${draftId}.ts via scripts/promote-scenario.ts. */
export const scenario: Scenario = ${JSON.stringify(scenario, null, 2)};
`;
  writeFileSync(join(promotedDir, `${draftId}.ts`), promotedFile, "utf8");
  regeneratePromotedIndex();

  console.log(`\nPromoted "${draftId}" into the live registry (src/lib/scenarios/promoted/${draftId}.ts).`);
  console.log("src/lib/scenarios/index.ts already imports promoted/ — no further wiring needed.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
